name: Build WeChatGuard Executable

on:
  push:
    tags:
      - 'v*'  # 触发标签以 v 开头
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 添加写入权限

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow pywin32 pyautogui  # 确保安装 pywin32
        
    - name: Generate icon
      run: |
        python generate_icon.py
        
    - name: Generate version info
      run: |
        python generate_version_info.py
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=src/icon/app_icon.ico --name="WeChatGuard_${{ github.ref_name }}" --version-file=version_info.txt src/main.py --hidden-import win32gui --hidden-import win32con  # 添加隐藏导入
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 添加 GitHub Token
      with:
        files: |
          dist/WeChatGuard_${{ github.ref_name }}.exe
        body: |
          ## 更新内容
          - 新增自动监控系统空闲时间
          - 达到设定阈值后自动进入守护模式
          - 优化了空闲时间检测逻辑
          - 改进了系统托盘图标状态显示
          - 修复了程序退出时的错误
