name: Build WeChatGuard Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller setuptools wheel
    
    - name: Extract version and build time
      id: get_version
      shell: bash
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "build_time=${BUILD_TIME}" >> $GITHUB_OUTPUT
    
    - name: Generate version_info.txt
      shell: pwsh
      run: |
        $version = "${{ steps.get_version.outputs.version }}"
        $version_parts = $version -replace '^v', '' -split '\.'
        $major = if ($version_parts.Length -gt 0) { $version_parts[0] } else { '1' }
        $minor = if ($version_parts.Length -gt 1) { $version_parts[1] } else { '0' }
        $patch = if ($version_parts.Length -gt 2) { $version_parts[2] } else { '0' }
        
        $version_info = @"
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($major, $minor, $patch, 0),
    prodvers=($major, $minor, $patch, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringEntry('CompanyName', '个人开发'),
            StringEntry('FileDescription', 'WeChat Guardian - 微信守护程序'),
            StringEntry('FileVersion', '$major.$minor.$patch.0'),
            StringEntry('InternalName', 'WeChatGuard'),
            StringEntry('LegalCopyright', ' 2024 个人开发'),
            StringEntry('OriginalFilename', 'WeChatGuard.exe'),
            StringEntry('ProductName', 'WeChat Guardian'),
            StringEntry('ProductVersion', '$major.$minor.$patch.0')
          ]
        )
      ]
    ),
    VarFileInfo([VarEntry('Translation', [2052, 1200])])
  ]
)
"@
        
        Set-Content -Path version_info.txt -Value $version_info
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=src/icon/app_icon.ico --name="WeChatGuard_${{ steps.get_version.outputs.version }}" --version-file=version_info.txt src/main.py
        ls dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/WeChatGuard_*.exe
        body: |
          ## 更新日志
          - 版本：${{ steps.get_version.outputs.version }}
          - 构建时间：${{ steps.get_version.outputs.build_time }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
